env:
  sim_steps: 10 # one sim step will be 2ps, number of simulations steps to take at a time
  samples_per_step: 5 #so every ligand is simulated for 512ps number of sim_steps to take, should be at least 128 to correctly sample mmgbsa scores
  movie_frames: 5 # number of snapshots to save per env step, ideally divides samples per step
  verbose: True
  tempdir : 'runs_implicit_moleculegrow/'
  overwrite_static : True
  equilibrate : False

systemloader:
  - module : PDBLigandSystemBuilder
  - pdb_file_name : 'rlmm/resources/adrp_apo.pdb'
  - ligand_file_name : 'rlmm/resources/adrp_ties.mol2'
  - explicit : False
#
#actions:
#  - module : FastRocsActionSpace
#  - host : "kontrol:8080"
#  - space_size : 50

actions:
  - module : MoleculePiecewiseGrow
  - atoms : ['C', 'O', "N", 'F', 'S', 'H', 'Br', 'Cl']
  - allow_removal : True
  - allowed_ring_sizes : [3,4,5,6,7,8]
  - allow_no_modification : False
  - allow_bonds_between_rings : False
  - starting_smiles : Cc1c([nH]c2c1c(ncn2)NC(=O)[C@@H](C)SCc3[nH]c(=O)c4ccccc4n3)C

obsmethods:
  - module : PDBFile

openmmWrapper:
  - module : MCMCOpenMMSimulationWrapper
  - n_steps : 50
  - hybrid : True
  - displacement_sigma : 0.5
  - ligand_pertubation_samples : 1
  - params :
      {
        'minMaxIters' : 0,
        'createSystem' : {
          'implicitSolvent': app.GBn2,
#          'nonbondedMethod': app.PME,
#           'ewaldErrorTolerance' : 0.0005,
          'nonbondedMethod': app.CutoffNonPeriodic,
           'rigidWater'  : True,
          'removeCMMotion' : True,
          'nonbondedCutoff': 1.0  * unit.nanometer,
          'constraints': app.HBonds,
        },
        'integrator': mm.LangevinIntegrator,
        'integrator_params': {
          'temperature': 310.15 * unit.kelvin,
          'collision_rate': 1.0 / unit.picoseconds,
          'timestep': 2.0 * unit.femtoseconds
        },
        'integrator_setConstraintTolerance': 0.00001,
        'platform_config' :
          {
                        'UseCpuPme' : 'false',
                        'Precision' : 'mixed',
#                        'DeterministicForces' : 'false',
#                        'UseBlockingSync' : 'false',
#                        'DeviceIndex' : "0"
        },
        'platform': mm.Platform.getPlatformByName('CUDA')
      }
