env:
  sim_steps: 1 # one sim step will be 2ps, number of simulations steps to take at a time
  samples_per_step: 30 #so every ligand is simulated for 512ps number of sim_steps to take, should be at least 128 to correctly sample mmgbsa scores
  movie_frames: 30 # number of snapshots to save per env step, ideally divides samples per step
  verbose: True
  tempdir : 'runs/'
  overwrite_static : True
  equilibrate : True

systemloader:
  - module : PDBLigandSystemBuilder
  - pdb_file_name : 'rlmm/resources/adrp_apo.pdb'
  - ligand_file_name : 'rlmm/resources/adrp_ties.mol2'
  - explicit : False

actions:
  - module : MoleculePiecewiseGrow
  - atoms : ['C', 'O', "N", 'F', 'S', 'H', 'Br', 'Cl']
  - allow_removal : True
  - allowed_ring_sizes : [3,4,5,6,7,8]
  - allow_no_modification : True
  - allow_bonds_between_rings : False
  - starting_smiles : Cc1c([nH]c2c1c(ncn2)NC(=O)[C@@H](C)SCc3[nH]c(=O)c4ccccc4n3)C

obsmethods:
  - module : PDBFile

openmmWrapper:
  - module : MCMCReplicaOpenMMSimulationWrapper
  - n_steps : 100
  - hybrid : True
  - displacement_sigma : 1
  - ligand_pertubation_samples : 10
  - params :
      {
        'minMaxIters' : 0,
        'createSystem' : {
          'implicitSolvent': app.GBn2,
#          'nonbondedMethod': app.PME,
          'nonbondedMethod': app.CutoffNonPeriodic,
           'rigidWater'  : True,
          'removeCMMotion' : True,
          'nonbondedCutoff': 1.5 * unit.nanometer,
          'constraints': app.HBonds,
        },
        'integrator': mm.LangevinIntegrator,
        'integrator_params': {
          'temperature': 310.15 * unit.kelvin,
          'collision_rate': 1.0 / unit.picoseconds,
          'timestep': 1.0 * unit.femtoseconds
        },
        'integrator_setConstraintTolerance': 0.00001,
        'platform_config' :
          {
                        'UseCpuPme' : 'false',
                        'Precision' : 'mixed',
#                        'DeterministicForces' : 'false',
#                        'UseBlockingSync' : 'false',
#                        'DeviceIndex' : "0"
        },
        'platform': mm.Platform.getPlatformByName('OpenCL')
      }
