env:
  sim_steps: 10 # one sim step will be 2ps, number of simulations steps to take at a time
  samples_per_step: 256 #so every ligand is simulated for 512ps number of sim_steps to take, should be at least 128 to correctly sample mmgbsa scores
  movie_frames: 64 # number of snapshots to save per env step, ideally divides samples per step
  verbose: True
  tempdir : 'runs/'

systemloader:
  - module : PDBLigandSystemBuilder
  - pdb_file_name : 'rlmm/resources/jak2/receptor.pdb'
  - ligand_file_name : 'rlmm/resources/jak2/crystal_ligand.mol2'

actions:
  - module : FastRocsActionSpace
  - host : "venti:8080"
  - space_size : 10

obsmethods:
  - module : PDBFile

openmmWrapper:
  - module : OpenMMSimulationWrapper
  - params :
      {
        'minMaxIters' : 0,
        'createSystem' : {
          'implicitSolvent': app.GBn2,
          'nonbondedMethod': app.CutoffNonPeriodic,
          'nonbondedCutoff': 1.0 * unit.nanometer,
          'constraints': app.HBonds,
        },
        'integrator': mm.LangevinIntegrator,
        'integrator_params': {
          'temperature': 310.15 * unit.kelvin,
          'collision_rate': 1.0 / unit.picoseconds,
          'timestep': 2.0 * unit.femtoseconds
        },
        'integrator_setConstraintTolerance': 0.00001,
        'platform_config' :
          {
                        'UseCpuPme' : 'false',
                        'Precision' : 'mixed',
                        'DeterministicForces' : 'false',
                        'UseBlockingSync' : 'false',
#                        'DeviceIndex' : "0"
        },
        'platform': mm.Platform.getPlatformByName('CUDA')
      }
